FROM oven/bun:1

WORKDIR  /user/src/app
ARG DATABASE_URL
COPY ./package ./package
COPY ./bun.lock  ./bub.lock

COPY ./package.json ./package.json
COPY  ./turbo.json /turbo.json

COPY ./app/web ./app/web

COPY . .
RUN bun install
RUN DATABASE_URL= ${DATABASE_URL} bun run build

EXPOSE 8081
CMD [ "bun" , "run", "start:frontend"]
