FROM oven/bun:1

WORKDIR  /user/src/app

COPY ./package ./package
COPY ./bun.lock  ./bub.lock

COPY ./package.json ./package.json
COPY  ./turbo.json /turbo.json

COPY ./app/backend ./app/backend

COPY . .
RUN bun install
RUN bun run db:migrate
 

EXPOSE 8080
CMD [ "bun" , "run", "start:backend"]
