name: Deploy The Backend

on:
  push:
    branches : [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
        - name : Checkout The Code
          uses : actions/checkout@
          
        - name: Docker Login
          uses : docker/login-action@v2
          with :
            username : ${{ secrets.DOCKERHUB_USERNAME }}
            password : ${{ secrets.DOCKERHUB_TOKEN }} 
